/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-10-28 23:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \r\n");
      out.write("<title>index</title>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    $(\"#flip1\").click(function(){\r\n");
      out.write("      $(\"#panel1\").fadeToggle();\r\n");
      out.write("      $(\"#panel2\").hide();\r\n");
      out.write("      $(\"#panel3\").hide();\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    $(\"#flip2\").click(function(){\r\n");
      out.write("      $(\"#panel2\").fadeToggle(\"slow\");\r\n");
      out.write("      $(\"#panel3\").hide();\r\n");
      out.write("      $(\"#panel1\").hide();\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    $(\"#flip3\").click(function(){\r\n");
      out.write("      $(\"#panel3\").fadeToggle(\"slow\");\r\n");
      out.write("      $(\"#panel2\").hide();\r\n");
      out.write("      $(\"#panel1\").hide();\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("    $(\"#cl\").click(function(){\r\n");
      out.write("      $(\"#login\").fadeToggle(\"slow\");\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\thtml{\r\n");
      out.write("\t\tfont-size:10px;\r\n");
      out.write("\t\tfont-family: sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t#navbar{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tbackground-color:black;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:55px;\r\n");
      out.write("\t\tcolor:white;\t\r\n");
      out.write("\t}\r\n");
      out.write("\th1{\r\n");
      out.write("\t\tfont-size:2.5rem;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tfont-style: italic;\r\n");
      out.write("\t\tmargin-left:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\ta{\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\tfont-size:1.7rem;\r\n");
      out.write("\t\tmargin-top:22.5px;\r\n");
      out.write("\t\tmargin-right:15px;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tpadding-left:10px;\r\n");
      out.write("\t\tborder-left: 1px solid white;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\ta:hover{\r\n");
      out.write("\t\ttext-decoration: underline;\r\n");
      out.write("\t\tcolor: blue;\r\n");
      out.write("\t}\r\n");
      out.write("\t#carousel{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tbackground-color:black;\r\n");
      out.write("\t\tbackground-image:url('static/pict4.jpg');\r\n");
      out.write("\t\tbackground-size: 100% 300px;\r\n");
      out.write("\t\tmargin-top:58px;\r\n");
      out.write("\t\tmargin-left:5px;\r\n");
      out.write("\t\tmargin-right:5px;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:300px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write("\t#menu{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("  \t\tflex-direction: row;\r\n");
      out.write("\t\tbackground-color:black;\r\n");
      out.write("\t\tmargin-top:361.5px;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:58px;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tz-index:3;\r\n");
      out.write("\t}\r\n");
      out.write("\tbutton{\r\n");
      out.write("\t\twidth:33.3%;\r\n");
      out.write("\t\tmargin: 5px;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\tbackground-color:lightgrey;\r\n");
      out.write("\t\tfont-size:1.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("\t#footer{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tbackground-image: url('static/cart.jpg');\r\n");
      out.write("\t\tbackground-size: 100% 300px;\r\n");
      out.write("\t\tmargin-top:423px;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:300px;\r\n");
      out.write("\t\tz-index:1;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      margin-top: 418px;\r\n");
      out.write("      width:100%;\r\n");
      out.write("      height:200px;\r\n");
      out.write("      background-color: black;\r\n");
      out.write("      color: white;\r\n");
      out.write("      /*display: none;*/\r\n");
      out.write("      opacity:0.85;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      z-index:2;\r\n");
      out.write("      padding-top:40px;\r\n");
      out.write("    }\r\n");
      out.write("    input{\r\n");
      out.write("        text-align:center;\r\n");
      out.write("      }\r\n");
      out.write("     tr,td{\r\n");
      out.write("     \tpadding:3px;\r\n");
      out.write("     }\r\n");
      out.write("      #login{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      background-color: black;\r\n");
      out.write("      padding-top:10px;\r\n");
      out.write("      width:20%;\r\n");
      out.write("      height:290px;\r\n");
      out.write("      margin-top:58.7px;\r\n");
      out.write("      margin-left:80%;\r\n");
      out.write("      opacity:0.8;\r\n");
      out.write("      z-index:2;\r\n");
      out.write("      display:none;\r\n");
      out.write("      }\r\n");
      out.write("      .log{\r\n");
      out.write("      \t width:267px; \r\n");
      out.write("      \t margin-left:5px; \r\n");
      out.write("      }\r\n");
      out.write("      .sub{\r\n");
      out.write("      \tmargin-left:118.5px;\r\n");
      out.write("      }\r\n");
      out.write("      #msg{\r\n");
      out.write("      \tcolor:white; \r\n");
      out.write("      \ttext-align:center; \r\n");
      out.write("      \twidth:100%; \r\n");
      out.write("      \tmargin-top:250px; \r\n");
      out.write("      \tfont-size:3.95rem;\r\n");
      out.write("      }\r\n");
      out.write("\t@media only screen and (max-width: 800px) {\r\n");
      out.write("      #login {\r\n");
      out.write("        width:100%;\r\n");
      out.write("        margin-left:0%;\r\n");
      out.write("        padding-top:10px;\r\n");
      out.write("      }  \r\n");
      out.write("      .log,.sub{\r\n");
      out.write("      \t  width:85%;\r\n");
      out.write("      \t  margin-left:9.5%;      \r\n");
      out.write("      }}\r\n");
      out.write("      @media only screen and (max-width: 400px){\r\n");
      out.write("      #msg {\r\n");
      out.write("      \t font-size:2.5rem;\r\n");
      out.write("      \t text-align:left;\r\n");
      out.write("      \t margin-top:235px;  \r\n");
      out.write("      }}\r\n");
      out.write("      @media only screen and (max-width: 400px){\r\n");
      out.write("      button{\r\n");
      out.write("\t\twidth:31%;\r\n");
      out.write("\t\tmargin: 5px;\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\tbackground-color:lightgrey;\r\n");
      out.write("\t}}\r\n");
      out.write("\t@media only screen and (min-width: 400px){\r\n");
      out.write("      #footer{\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t\tbackground-size: 100% 400px ;\r\n");
      out.write("\t}\r\n");
      out.write("\t#msg{\r\n");
      out.write("      \tfont-size:3.5rem;\r\n");
      out.write("      }\r\n");
      out.write("\t}\r\n");
      out.write("\t@media only screen and (min-height: 800px){\r\n");
      out.write("      #footer{\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tbackground-size: 100% 400px ;\r\n");
      out.write("\t}\r\n");
      out.write("\t#msg{\r\n");
      out.write("      \tfont-size:4.5rem;\r\n");
      out.write("      }\r\n");
      out.write("\t}\r\n");
      out.write("      \r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var pictures=[\"url('static/pict4.jpg')\",\"url('static/pict5.jpg')\",\"url('static/pict3.jpg')\"];\r\n");
      out.write("    counter=0;\r\n");
      out.write("    \r\n");
      out.write("    function bc(){\r\n");
      out.write("          document.getElementById('carousel').style.backgroundImage=pictures[counter];\r\n");
      out.write("          counter+=1;\r\n");
      out.write("          if(counter==3){\r\n");
      out.write("            counter=0;\r\n");
      out.write("          }\r\n");
      out.write("    }\r\n");
      out.write("    setInterval(function(){bc()},3000);\r\n");
      out.write("\r\n");
      out.write("    var var1=0;\r\n");
      out.write("    var vars=[0,0,0,0];\r\n");
      out.write("    function ons(id){\r\n");
      out.write("      if(vars[id]==0){\r\n");
      out.write("        vars[id]=1;\r\n");
      out.write("        document.getElementById('flip'+id).style.backgroundColor='black';\r\n");
      out.write("        document.getElementById('flip'+id).style.color='white';\r\n");
      out.write("        document.getElementById('flip'+id).style.fontSize='2em';\r\n");
      out.write("      }\r\n");
      out.write("      else{\r\n");
      out.write("        vars[id]=0\r\n");
      out.write("        document.getElementById('flip'+id).style.backgroundColor='lightgrey';\r\n");
      out.write("        document.getElementById('flip'+id).style.color='black';\r\n");
      out.write("        document.getElementById('flip'+id).style.fontSize='1.3rem';\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    function onl(id){\r\n");
      out.write("      if(var1==0){\r\n");
      out.write("        var1=1;\r\n");
      out.write("        document.getElementById(id).style.color='blue';\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("      else{\r\n");
      out.write("        var1=0\r\n");
      out.write("        document.getElementById(id).style.color='white';\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    function off(id){\r\n");
      out.write("        vars[id]=0\r\n");
      out.write("        document.getElementById('flip'+id).style.backgroundColor='lightgrey';\r\n");
      out.write("        document.getElementById('flip'+id).style.color='black';\r\n");
      out.write("        document.getElementById('flip'+id).style.fontSize='1.3rem';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function moveover(id){\r\n");
      out.write("      if(vars[id]==0){\r\n");
      out.write("    \t  document.getElementById('flip'+id).style.backgroundColor='grey';\r\n");
      out.write("    \t  document.getElementById('flip'+id).style.color='white';\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("    function moveout(id){\r\n");
      out.write("      if(vars[id]==0){\r\n");
      out.write("    \t  document.getElementById('flip'+id).style.backgroundColor='lightgrey';\r\n");
      out.write("    \t  document.getElementById('flip'+id).style.color='black';\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function calco(val){\r\n");
      out.write("    \tif(val>10){\r\n");
      out.write("    \t\tdocument.getElementById('demo').value=(val*1);\r\n");
      out.write("    \t}\r\n");
      out.write("    \telse{\r\n");
      out.write("    \t\tdocument.getElementById('demo').value=(val*1.5);\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    setInterval(function(){calco(document.getElementById('ca').value)},500);\r\n");
      out.write("    \r\n");
      out.write("    function calcul(val){\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(val=='SETTIMANALE'){\r\n");
      out.write("    \t\t document.getElementById('dem').value='25';\r\n");
      out.write("    \t}\r\n");
      out.write("    \telse if(val=='MENSILE'){\r\n");
      out.write("    \t\t document.getElementById('dem').value='75';\r\n");
      out.write("    \t}\r\n");
      out.write("    \telse if(val=='ANNUALE'){\r\n");
      out.write("    \t\t document.getElementById('dem').value='250';\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    setInterval(function(){calcul( document.getElementById('duration').value)},500);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"navbar\">\r\n");
      out.write("\t\t<h1>URBAN PAVIA</h1>\r\n");
      out.write("\t\t<a id=\"cl\" href=\"#\" onclick=\"onl('cl')\">Accedi</a>\r\n");
      out.write("\t\t<a  href=\"activate.jsp\">Attiva il tuo titolo di viaggio</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t    <div id=\"login\">\r\n");
      out.write("      <form class=\"\" action=\"Login\" method=\"post\" required >\r\n");
      out.write("        <table class=\"log\">\r\n");
      out.write("          <tr >\r\n");
      out.write("            <td><input class=\"log\" type=\"text\" name=\"username\" value=\"\" placeholder=\"username\" required></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>&nbsp</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><input class=\"log\"  type=\"password\" name=\"password\" value=\"\" placeholder=\"password\" required></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>&nbsp</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr >\r\n");
      out.write("            <td><input class=\"sub\" type=\"submit\" name=\"\" value=\"Login\" ></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div id=\"carousel\">\r\n");
      out.write("\t\t      <h1 id=\"msg\" >ACQUISTA UN TITOLO DI VIAGGIO</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<button id=\"flip1\" id=\"flip1\" onclick=\"ons(1);off(2);off(3);\" onmouseover=\"moveover(1)\" onmouseout=\"moveout(1)\">BIGLIETTO SINGOLO</button>\r\n");
      out.write("\t\t<button id=\"flip2\"  onclick=\"ons(2);off(1);off(3);\" onmouseover=\"moveover(2)\" onmouseout=\"moveout(2)\">BIGLIETTO CUMULATIVO</button>\r\n");
      out.write("\t\t<button id=\"flip3\" onclick=\"ons(3);off(1);off(2);\" onmouseover=\"moveover(3)\" onmouseout=\"moveout(3)\">ABBONAMENTO</button>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footer\"></div>\r\n");
      out.write("\t<div id=\"panel1\" class=\"panel\" style=\"display:none\">\r\n");
      out.write("\t<form style=\"font-size:1.4em\" class=\"\" action=\"payment.jsp\" method=\"post\">\r\n");
      out.write("        Prezzo: <input style=\"color:black\" id=\"de\" type=\"text\" name=\"price\" value=\"1.50\"  readonly=\"readonly\"> &euro;<br><br>\r\n");
      out.write("        <input style=\"display:none\" id=\"type\" type=\"text\" name=\"type\" value=\"single\">\r\n");
      out.write("        <input style=\"color:black\" type=\"submit\" name=\"\" value=\"Paga\">\r\n");
      out.write("      </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"panel2\" class=\"panel\" style=\"display:none\">\r\n");
      out.write("\t\t<form  style=\"font-size:1.4em\" class=\"\" action=\"payment.jsp\" method=\"post\">\r\n");
      out.write("        Numero di viaggi:\r\n");
      out.write("        <select style=\"color:black\" name=\"tripsNum\" id=\"ca\" onclick=\"if(this.value>10){document.getElementById('demo').value=(this.value*1);}else{document.getElementById('demo').value=(this.value*1.5);}\" required>\r\n");
      out.write("          <option value=5>5</option>\r\n");
      out.write("          <option value=10>10</option>\r\n");
      out.write("          <option value=20>20</option>\r\n");
      out.write("          <option value=50>50</option>\r\n");
      out.write("          <option value=100>100</option>\r\n");
      out.write("        </select><br><br>\r\n");
      out.write("      Prezzo: <input style=\"color:black\" id=\"demo\" type=\"text\" name=\"price\" value=\"7.5\"  readonly=\"readonly\"> &euro;<br><br>\r\n");
      out.write("      <input style=\"display:none\" type=\"text\" name=\"type\" value=\"cumulative\">\r\n");
      out.write("      <input style=\"color:black;\" type=\"submit\" name=\"\" value=\"Paga\">\r\n");
      out.write("      </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"panel3\" class=\"panel\" style=\"display:none; padding-top:20px\">\r\n");
      out.write("\t\t<form  style=\"font-size:1.4em;\" class=\"\" action=\"payment.jsp\" method=\"post\">\r\n");
      out.write("        <table style=\"margin:auto; border-collapse: collapse;\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class='td' style=\"text-align:right;\">Nome:</td>\r\n");
      out.write("            <td class='td'><input style=\"color:black\" type=\"text\" name=\"name\" value=\"\" required> </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class='td' style=\"text-align:right;\">Cognome:</td>\r\n");
      out.write("            <td class='td'><input style=\"color:black\" type=\"text\" name=\"surname\" value=\"\" required> </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("            <td class='td' style=\"text-align:right;\">Durata:</td>\r\n");
      out.write("            <td class='td'><select style=\"color:black\" name=\"duration\" id=\"duration\" onclick=\"calcul(this.value)\">\r\n");
      out.write("              <option value='SETTIMANALE'>SETTIMANALE</option>\r\n");
      out.write("              <option value='MENSILE'>MENSILE</option>\r\n");
      out.write("              <option value='ANNO'>ANNUALE</option>\r\n");
      out.write("            </select></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class='td'><br> </td>\r\n");
      out.write("            <td class='td'> </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class='td' style=\"text-align:right;\">Prezzo: </td>\r\n");
      out.write("            <td class='td'><input style=\"color:black\" id=\"dem\" type=\"text\" name=\"price\" value=\"25\"  readonly=\"readonly\">&euro;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td class='td' style=\"text-align:left;\"></td>\r\n");
      out.write("            <td class='td'></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("\r\n");
      out.write("            <td class='td'></td>\r\n");
      out.write("            <input style=\"display:none\" type=\"text\" name=\"type\" value=\"pass\">\r\n");
      out.write("            <td class='td'><input style=\"color:black\" type=\"submit\" name=\"\" value=\"Paga\"></td>\r\n");
      out.write("\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
